global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: game-server-monitor

rule_files:
  - alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  - job_name: game-server
    static_configs:
      - targets: ["localhost:3008"]
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
