apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: game-server
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsiYXV0aCI6ImZha2VfY3JlZGVudGlhbHMifX19
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-server
  namespace: game-server
imagePullSecrets:
  - name: registry-credentials
