apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-server
  namespace: game-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: game-server
  namespace: game-server
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: game-server
  namespace: game-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: game-server
subjects:
  - kind: ServiceAccount
    name: game-server
    namespace: game-server
